Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provider :managed do |managed, override|
    managed.server = ENV['MANAGED_IP']
    override.vm.box = 'tknerr/managed-server-dummy'
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "./.ssh/private.key"
  end
  config.nfs.functional = false

  # Override the default sync'd folder, supressing NFS, then allow rsync
  config.vm.allowed_synced_folder_types = [:rsync]
  config.vm.synced_folder '.', '/vagrant', type: "rsync", rsync__exclude: [".git/", ".vagrant/"]  
  
  config.vm.box_check_update = false
end